language: php

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update --no-interaction
    - composer update --no-interaction --prefer-dist
script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then vendor/bin/phpstan analyse --configuration phpstan.neon --level 7 src/; fi
    - vendor/bin/tester test/cases
